### ISSUE TITLE
Error when inference

### ISSUE THREAD

**Issue by huytuong010101** [xml94/PlantCLEF2022#1]
Thank you for perfect repository,
I try to inference an example with this code after load model following `main_finetune.py`
```
x = torch.randn(1, 3, 224, 224)
x = x.to(device)
model_without_ddp.eval()
with torch.no_grad():
    output = model_without_ddp(x)
    print(output.shape)
```
but i got this error, can you help me solve this problem,?
```
Traceback (most recent call last):
  File "main_finetune.py", line 296, in <module>
    main(args)
  File "main_finetune.py", line 284, in main
    output = model_without_ddp(x)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/timm/models/vision_transformer.py", line 468, in forward
    x = self.forward_head(x)
  File "/usr/local/lib/python3.7/dist-packages/timm/models/vision_transformer.py", line 463, in forward_head
    x = self.fc_norm(x)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/normalization.py", line 190, in forward
    input, self.normalized_shape, self.weight, self.bias, self.eps)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py", line 2503, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: Given normalized_shape=[1024], expected input with shape [*, 1024], but got input of size[1]
```

**Comment by xml94** [comment]
Hi, @huytuong010101 ,
I think I do not use "model_without_dpp", instead I use "model" directly.
If you did not solve your problem, please tell me.

**Comment by huytuong010101** [comment]
Thank you. It worked
